<?php
	if (date('G') > 21 && date('G') < 3){
		echo "<table><tbody><tr><td class='bg1'><img src='_pgdat/Night/scroll1.png'></td><td class='main' style='background-image: url(\\\"_pgdat/Night/scroll.png\\\");'><div class='body'><a href='index.php'>Home</a><a href='journal.php'>Journal</a><a href='projects.php'>Projects</a><a href='http://www.youtube.com/user/eNnillaGotBored' style='float:right'><img src='_pgdat/youtube.png' /></a><a href='https://twitter.com/King_eNnilla' style='float:right'><img src='_pgdat/twitter.png' /></a><a href='https://www.facebook.com/AnonyD3RP612' style='float:right'><img src='_pgdat/facebook.png' /></a><a href='http://dev.bukkit.org/profiles/eNnillaMS/bukkit-plugins/' style='float:right'>BukkitDev</a><a href='../index.php' style='float:right'>Main Portal</a></div></td><td class='bg2'><img src='_pgdat/Night/scroll2.png'></td></tr></tbody></table>";
	} else if (date('G') > 3 && date('G') < 9){
		echo "<table><tbody><tr><td class='bg1'><img src='_pgdat/Morning/scroll1.png'></td><td class='main' style='background-image: url(\\\"_pgdat/Morning/scroll.png\\\");'><div class='body'><a href='index.php'>Home</a><a href='journal.php'>Journal</a><a href='projects.php'>Projects</a><a href='http://www.youtube.com/user/eNnillaGotBored' style='float:right'><img src='_pgdat/youtube.png' /></a><a href='https://twitter.com/King_eNnilla' style='float:right'><img src='_pgdat/twitter.png' /></a><a href='https://www.facebook.com/AnonyD3RP612' style='float:right'><img src='_pgdat/facebook.png' /></a><a href='http://dev.bukkit.org/profiles/eNnillaMS/bukkit-plugins/' style='float:right'>BukkitDev</a><a href='../index.php' style='float:right'>Main Portal</a></div></td><td class='bg2'><img src='_pgdat/Morning/scroll2.png'></td></tr></tbody></table>";
	} else if (date('G') > 9 && date('G') < 15){
		echo "<table><tbody><tr><td class='bg1'><img src='_pgdat/Day/scroll1.png'></td><td class='main' style='background-image: url(\\\"_pgdat/Day/scroll.png\\\");'><div class='body'><a href='index.php'>Home</a><a href='journal.php'>Journal</a><a href='projects.php'>Projects</a><a href='http://www.youtube.com/user/eNnillaGotBored' style='float:right'><img src='_pgdat/youtube.png' /></a><a href='https://twitter.com/King_eNnilla' style='float:right'><img src='_pgdat/twitter.png' /></a><a href='https://www.facebook.com/AnonyD3RP612' style='float:right'><img src='_pgdat/facebook.png' /></a><a href='http://dev.bukkit.org/profiles/eNnillaMS/bukkit-plugins/' style='float:right'>BukkitDev</a><a href='../index.php' style='float:right'>Main Portal</a></div></td><td class='bg2'><img src='_pgdat/Day/scroll2.png'></td></tr></tbody></table>";
	} else if (date('G') > 15 && date('G') < 21){
		echo "<table><tbody><tr><td class='bg1'><img src='_pgdat/Dusk/scroll1.png'></td><td class='main' style='background-image: url(\\\"_pgdat/Dusk/scroll.png\\\");'><div class='body'><a href='index.php'>Home</a><a href='journal.php'>Journal</a><a href='projects.php'>Projects</a><a href='http://www.youtube.com/user/eNnillaGotBored' style='float:right'><img src='_pgdat/youtube.png' /></a><a href='https://twitter.com/King_eNnilla' style='float:right'><img src='_pgdat/twitter.png' /></a><a href='https://www.facebook.com/AnonyD3RP612' style='float:right'><img src='_pgdat/facebook.png' /></a><a href='http://dev.bukkit.org/profiles/eNnillaMS/bukkit-plugins/' style='float:right'>BukkitDev</a><a href='../index.php' style='float:right'>Main Portal</a></div></td><td class='bg2'><img src='_pgdat/Dusk/scroll2.png'></td></tr></tbody></table>";
	}
?>